language: <lang> # must be the same as template e.g cs, go, java
version: 3.0

usesNamespace: true
canInject: true

moduleLevelVariablePrefix: "_"

defaultImports: [
  "System;"
]

types:
  -interface:
    key: "interface"   
    namePostfix: Repository
    namePrefix: I
  -models:
    key: "model"      
    namePostfix: Model
  -repository:   
    key: "repository"   
    namePostfix: Repository
    imports: [
      "using {{ .Code.RootNamespace }}.Extensions"
    ]
  -service:
    key: "service"  
    namePostfix: "Service"
  -controller:
    namePostfix: "Controller" 
    imports: [
      "using {{ .Code.RootNamespace }}.Extensions"
    ]
  -extension:
    namePostfix: "Extension"      
    namespace: "{{ .Code.RootNamespace }}.Extensions"

inject:  
  -logging:
    name: ILogger<{{ .Name }}>
    keys: [logging]
    language: cs      
    propertyName: logger
    imports: [
      "using Microsoft.Logging"
    ]

## only on init
importCommands: [
  "dotnet ...."
]

## only on init
preferredPackages:
  -mssql: ["Microsoft.Data"]
  -postgres: ["<package>"]
  -metrics: ["metrics"]
  -logging: ["logging"]

casing:
  -Default: Pascal
  -Method: Pascal
  -Variable: Camel
  -Property: Pascal
## maps datatype to language type
## can be a mix of mssql, postgres, mysql etc


defaultDataTypes:
  -strings: {notNull: string, Nullable: string, NullableAlternative: string}
  -integers: {notNull: int, Nullable: int?, NullableAlternative: Nullable<int>}
  -floats: {notNull: decimal, Nullable: decimal?, NullableAlternative: Nullable<decimal>}

dataTypes: 
  -string: {NotNull: string, Nullable: string, NullableAlternative: string}
  -bigint: Int64
  -binary: Byte[]
  -bit: bool
  -char: char
  -date: DateTime
  -datetime: DateTime
  -datetime2: DateTime
  -datetimeoffset: DateTime
  -decimal: decimal
  -float: decimal
  -geography: string
  -geometry: string
  -image: string
  -int: int
  -money: decimal
  -nchar: string
  -ntext: string
  -numeric: decimal
  -nvarchar: string
  -real: decimal
  -smalldatetime: decimal
  -smallint: decimal
  -smallmoney: decimal
  -text: string
  -time: DateTime
  -timestamp: string
  -tinyint: number
  -uniqueidentifier: Guid
  -varbinary: Byte[]
  -varchar: string
  -xml: XElement