configVersion: 3.0
version: "3.0.0-beta1"

name: modelhelper/cli 

locations:
  model: "./core/models/{{.Name | singular | kebab}}" # relative to the .modelhelper project folder
  core-command: ./core/commands 
  core-query: ./core/query 
  ports-controller: ./ports/api/controllers 
  ports-validator: ./ports/api/validators 
  features: ./features/{.Name | singular | kebab} 
