configVersion: 3.0
appVersion: 3.0

developer:
  name: Hans-Petter Eitvet
  email: nothing
  githubAccountName: hp-e

templates:
  shared:
  global:
    location: ./templates

languages:
  definitions: ./languages


logging:
  enabled: true

defaultConnection: patest01
connections: 
  patest01:
    type: mssql
    connectionString: Data Source=patest01;Password={{ENV:PWD_PATOLAB}};User name=Test
    connection:
      userId: test
      pwd: "%**PWD_PATOLAB**%"
      datasource: patest01
      port: 1243

defaultSource: patolab
sources:
  patolab:
    connection: lab
    connectionString: lab
    name: patolab_test
    # connection: Data Source=patest01;Password=%**PWD_PATOLAB**%;User name=Test
    schema: dbo
    schemas: [
      dbo
      owner
    ]
    entities:
      - entity1
    type: database
    mapping: 
      IsActive:
        Name: "IsActive"
        isIgnored: true
        trueValue: 1 | true | yes
        falseValue: 0 | false | no
        deletedMarker: true
      CreatedOn:
        name: "CreatedOn"  
        isIgnored: true        
        isCreationDate: true    
    groups:
      histology:
        items: [
          entity_1
          entity_2
          entity_3
        ]

        options:
          -option_1: value_1

defaults:
  # code:
  #   -cs:
  #     globalVariablePrefix: "_"          
  keys:
    interface:
      key: "interface"   
      postfix: Repository
      prefix: I
    models:
      key: "model"      
      postfix: Model
    repository:   
      key: "repository"   
      postfix: Repository
    service:
      key: "service"  
      postfix: "Service"