# configuration for databases

dataTypes:
  -postgres:
    strings: [varchar, text]
    integers: [int]
    floats: [int]
  -mssql:
    strings: [varchar, text, nvarchar]
    integers: [int]
    floats: [int]