language: <lang> # must be the same as template e.g cs, go, java
version: 3

useNamespace: true
moduleLevelVariable: _{{ variableName}}

preferredPackages:
  mssql: Microsoft.Data
  postgres: <package>
  metrics: 


datatypes: 
  bigint: Int64
  binary: Byte[]
  bit: bool
  char: char
  date: DateTime
  datetime: DateTime
  datetime2: DateTime
  datetimeoffset: DateTime
  decimal: decimal
  float: decimal
  geography: string
  geometry: string
  image: string
  int: int
  money: decimal
  nchar: string
  ntext: string
  numeric: decimal
  nvarchar: string
  real: decimal
  smalldatetime: decimal
  smallint: decimal
  smallmoney: decimal
  text: string
  time: DateTime
  timestamp: string
  tinyint: number
  uniqueidentifier: Guid
  varbinary: Byte[]
  varchar: string
  xml: XElement